export const STORAGE_PROVIDER = Symbol('STORAGE_PROVIDER');
export const FILE_EVENT_SERVICE = Symbol('FILE_EVENT_SERVICE');
export const FILE_SERVICE = Symbol('FILE_SERVICE');
export const DISTRIBUTED_LOCK_SERVICE = Symbol('DISTRIBUTED_LOCK_SERVICE');
export const STORAGE_CLEANUP_TASK = Symbol('STORAGE_CLEANUP_TASK');
