services:
  ecohatch-iam-service:
    build:
      dockerfile: ./docker/production/Dockerfile.node
      context: .
      args:
        - APP_NAME=@ecohatch/iam-service
        - APP_DIR=api/iam-service
        - PORT=5001
    container_name: ecohatch-iam-service-con-dev
    image: ecohatch-iam-service:dev
    restart: always
    ports:
      - 5001:5001
  environment:
