// Dependency Injection Tokens
const TRANSLATOR_SERVICE = Symbol('TRANSLATOR_SERVICE');
const TRANSLATIONS_FILENAME = Symbol('TRANSLATIONS_FILENAME');
const TRANSLATION_KEY_FORMATTER_SERVICE = Symbol(
  'TRANSLATION_KEY_FORMATTER_SERVICE'
);
const TRANSLATION_KEY_SEPARATOR = '__?args=';

export {
  TRANSLATOR_SERVICE,
  TRANSLATIONS_FILENAME,
  TRANSLATION_KEY_SEPARATOR,
  TRANSLATION_KEY_FORMATTER_SERVICE,
};
