export const USER_ACCOUNT_SERVICE = Symbol('USER_ACCOUNT_SERVICE');
export const AUTH_SERVICE = Symbol('AUTH_SERVICE');
export const REFRESH_TOKEN_SERVICE = Symbol('REFRESH_TOKEN_SERVICE');
export const LOGIN_ATTEMPT_SERVICE = Symbol('LOGIN_ATTEMPT_SERVICE');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const USER_LOGGED_IN_DEVICE_SERVICE = Symbol(
  'USER_LOGGED_IN_DEVICE_SERVICE'
);
export const COOKIE_SERVICE = Symbol('COOKIE_SERVICE');
