/**
 * Configuration(Environment variables) keys
 */
enum Config {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  API_DEFAULT_VERSION = 'API_DEFAULT_VERSION',
  DEBUG_MODE = 'DEBUG_MODE',
  GRACEFUL_SHUTDOWN_TIMEOUT = 'GRACEFUL_SHUTDOWN_TIMEOUT',
  LOCALIZATION_KEY = 'LOCALIZATION_KEY',
  LOCALIZATION_FALLBACK_LANGUAGE = 'LOCALIZATION_FALLBACK_LANGUAGE',
  DATABASE_URL = 'DATABASE_URL',
  DATABASE_MAX_RETRIES = 'DATABASE_MAX_RETRIES',
  DATABASE_RETRY_DELAY = 'DATABASE_RETRY_DELAY',
  DATABASE_MAX_RETRY_DELAY = 'DATABASE_MAX_RETRY_DELAY',
  PRISMA_SCHEMA_PATH = 'PRISMA_SCHEMA_PATH',
  SWAGGER_USERNAME = 'SWAGGER_USERNAME',
  SWAGGER_PASSWORD = 'SWAGGER_PASSWORD',
  NPM_PACKAGE_VERSION = 'npm_package_version',
  NPM_PACKAGE_DESCRIPTION = 'npm_package_description',
  CACHE_URL = 'CACHE_URL',
  ADMIN_USER_EMAIL = 'ADMIN_USER_EMAIL',
  ADMIN_USER_PASSWORD = 'ADMIN_USER_PASSWORD',
  SYSTEM_USER_EMAIL = 'SYSTEM_USER_EMAIL',
  SYSTEM_USER_PASSWORD = 'SYSTEM_USER_PASSWORD',
  MAX_LOGIN_ATTEMPTS_ALLOWED = 'MAX_LOGIN_ATTEMPTS_ALLOWED',
  LOGIN_ATTEMPT_LOCKOUT_DURATION_MILLS = 'LOGIN_ATTEMPT_LOCKOUT_DURATION_MILLS',
  JWT_ACCESS_PRIVATE_KEY = 'JWT_ACCESS_PRIVATE_KEY',
  JWT_ACCESS_PUBLIC_KEY = 'JWT_ACCESS_PUBLIC_KEY',
  JWT_REFRESH_PRIVATE_KEY = 'JWT_REFRESH_PRIVATE_KEY',
  JWT_ACCESS_EXPIRATION_TIME = 'JWT_ACCESS_EXPIRATION_TIME',
  JWT_REFRESH_EXPIRATION_TIME = 'JWT_REFRESH_EXPIRATION_TIME',
  JWT_ISSUER = 'JWT_ISSUER',
  JWT_AUDIENCE = 'JWT_AUDIENCE',
  JWKS_URL = 'JWKS_URL',
}

export { Config };
