export const PERMISSION_GROUP_SERVICE = Symbol('PERMISSION_GROUP_SERVICE');
export const PERMISSION_SERVICE = Symbol('PERMISSION_SERVICE');
export const ADMIN_PERMISSION_SERVICE = Symbol('ADMIN_PERMISSION_SERVICE');
export const ADMIN_GROUP_PERMISSION_SERVICE = Symbol(
  'ADMIN_GROUP_PERMISSION_SERVICE'
);
