/**
 * Configuration(Environment variables) keys
 */
export enum Config {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  API_DEFAULT_VERSION = 'API_DEFAULT_VERSION',
  DEBUG_MODE = 'DEBUG_MODE',
  GRACEFUL_SHUTDOWN_TIMEOUT = 'GRACEFUL_SHUTDOWN_TIMEOUT',
  LOCALIZATION_KEY = 'LOCALIZATION_KEY',
  LOCALIZATION_FALLBACK_LANGUAGE = 'LOCALIZATION_FALLBACK_LANGUAGE',
  SWAGGER_USERNAME = 'SWAGGER_USERNAME',
  SWAGGER_PASSWORD = 'SWAGGER_PASSWORD',
  NPM_PACKAGE_VERSION = 'npm_package_version',
  NPM_PACKAGE_DESCRIPTION = 'npm_package_description',
  CACHE_URL = 'CACHE_URL',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_REGION = 'AWS_REGION',
  AWS_S3_ENDPOINT = 'AWS_S3_ENDPOINT',
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',
  UPLOAD_FILE_URL_EXPIRATION = 'UPLOAD_FILE_URL_EXPIRATION',
  DATABASE_URL = 'DATABASE_URL',
  DATABASE_MAX_RETRIES = 'DATABASE_MAX_RETRIES',
  DATABASE_RETRY_DELAY = 'DATABASE_RETRY_DELAY',
}
