/**
 * Configuration(Environment variables) keys
 */
enum Config {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  API_DEFAULT_VERSION = 'API_DEFAULT_VERSION',
  DEBUG_MODE = 'DEBUG_MODE',
  GRACEFUL_SHUTDOWN_TIMEOUT = 'GRACEFUL_SHUTDOWN_TIMEOUT',
  LOCALIZATION_KEY = 'LOCALIZATION_KEY',
  LOCALIZATION_FALLBACK_LANGUAGE = 'LOCALIZATION_FALLBACK_LANGUAGE',
  SWAGGER_USERNAME = 'SWAGGER_USERNAME',
  SWAGGER_PASSWORD = 'SWAGGER_PASSWORD',
  NPM_PACKAGE_VERSION = 'npm_package_version',
  NPM_PACKAGE_DESCRIPTION = 'npm_package_description',
  CACHE_URL = 'CACHE_URL',
}

export { Config };
